import { StateGraph } from "@langchain/langgraph";

/**
 * The internal state of the Research Agent.
 * Tracks the industry, specific pain points found, and the scores.
 */
export interface ResearchState {
    /** The target niche or industry being researched */
    niche: string;

    /** Current list of search queries generated by the agent */
    queries: string[];

    /** Raw search results aggregated from Google Search */
    searchResults: string[];

    /** Structured pain points extracted from results */
    painPoints: Array<{
        problem: string;
        why_it_hurts: string;
        pain_score: number; // 1-10
    }>;

    /** Evaluation scores for the niche */
    scores: {
        marketSize: number;     // 1-10
        competition: number;    // 1-10
        willingnessToPay: number; // 1-10
        overall: number;        // Calculated average
    };

    /** Descriptive research notes summarizing findings */
    researchNotes: string;

    /** Current agent status */
    status: 'researching' | 'analyzing' | 'scoring' | 'validated' | 'rejected' | 'failed';

    /** Any error messages encountered */
    error?: string;

    /** Extra structured context from analysis */
    findings?: any;
}

/**
 * Reducer-like logic for state updates (optional but good for complex updates)
 */
export const researchStateChannels = {
    niche: null,
    queries: (current: string[], next: string[]) => next,
    searchResults: (current: string[], next: string[]) => (current || []).concat(next),
    painPoints: (current: any[], next: any[]) => next,
    scores: null,
    researchNotes: null,
    status: null,
    error: null,
    findings: null
};
